# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DSkglDkK15FRRxMhcckvANpBXN4G9Ld0
"""

import pandas as pd

def extraer_datos(ruta_csv):
    """Extrae los datos desde un archivo CSV"""
    datos = pd.read_csv(ruta_csv, encoding='latin-1')
    return datos

def transformar_datos(datos):
    """Realiza las transformaciones necesarias a los datos"""
    # Ejemplo: Convertir tipos de datos o manejar valores nulos
    datos = datos.dropna()  # Eliminar filas con valores nulos como ejemplo
    return datos

def cargar_datos():
    """Ejemplo de función que podría cargar los datos transformados a una base de datos"""
    # Aquí podrías definir lógica para cargar los datos transformados a otro destino.
    pass